apiVersion: v1
kind: Pod
metadata:
  name: jenkins-kaniko
  namespace: applications  # Namespace belirtildi
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      # Jenkins konfigürasyonları
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - "/kaniko/executor"  # Kaniko executor'ını başlatıyoruz
      args:
        - "--context=."  # Dockerfile'ın bulunduğu dizin
        - "--dockerfile=Dockerfile"  # Dockerfile'ın adı
        - "--destination=suleonal/python-app:1.0.6"  # Docker Hub'a push edilecek image
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker  # Docker cred. secrets
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-docker-config  # Docker Hub secrets
