apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: databases
spec:
  schedule: "38 12 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgresql-backup
              image: suleonal/aws-postgre-cli:latest
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: postgresql-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: postgresql-user
                - name: POSTGRES_DB
                  value: "app_db"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: aws-access-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: aws-secret-key
                - name: AWS_DEFAULT_REGION
                  value: "eu-central-1" 
                - name: S3_BUCKET
                  value: "workspace-docker-bucket"
              command:
                - /bin/bash
                - -c
                - |
                  TIMESTAMP=$(date "+%Y-%m-%d-%H%M%S")
                  BACKUP_FILE="/tmp/db_backup_${TIMESTAMP}.sql"

                  export PGPASSWORD=$POSTGRES_PASSWORD
                  echo "PostgreSQL yedeği oluşturuluyor..."
                  pg_dump -U $POSTGRES_USER -d $POSTGRES_DB -h postgres-postgresql.databases.svc.cluster.local > $BACKUP_FILE

                  echo "Yedek dosyası S3'e yükleniyor..."
                  aws s3 cp $BACKUP_FILE s3://$S3_BUCKET/

                  echo "Yedekleme işlemi tamamlandı!"
          restartPolicy: OnFailure
