apiVersion: v1
kind: Secret
metadata:
  name: museum-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: python
  type: helm
  url: http://helm-repo-chartmuseum.default.svc.cluster.local:8080
