apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: python
spec:
  description: "Python project"
  sourceRepos:
    - 'http://helm-repo-chartmuseum.default.svc.cluster.local:8080'
  destinations:
    - namespace: applications
      server: 'https://kubernetes.default.svc'
