pipeline {
    agent any
    environment {
        APP_NAME = "python-web-app"
        REPOSITORY = "https://github.com/suleonal/python-web-app.git"
        VERSION = "1.0.${env.BUILD_ID}"
	DOCKER_REPO = 'suleonal/python-web-app'
	IMAGE = ""
        FULL_CHART_NAME = "${APP_NAME}-${VERSION}.tgz"
    }
    stages {
	stage('Print Working Directory and List Files') {
            steps {
                script {
                    sh 'pwd'
                    
                    sh 'ls -l'
                }
            }
        }
	/*stage('Kaniko Build & Push Image') {
            steps {
                container('kaniko') {
                    script {
                        sh '''
			/kaniko/executor --context 'pwd' --dockerfile 'pwd'/Dockerfile  --destination https://index.docker.io/v1/suleonal/python-web-app:1.0.1
                        '''
                    }
                }
            }
        }*/
	stage('Fetch Git Version') {
            steps {
                script {
                    env.GIT_COMMIT_SHORT = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    env.APP_VERSION = "1.0.0" 
            	    env.APP_VERSION = "1.0"

                    env.DOCKER_TAGS = "${env.APP_VERSION}.${env.GIT_COMMIT_SHORT}"

                    echo "Application Version: ${env.APP_VERSION}"
                    echo "Major Minor Version: ${env.MAJOR_MINOR_VERSION}"
                    echo "Docker Tags: ${env.DOCKER_TAGS}"
                }
            }
        }
        stage('Kaniko Build & Push Image') {
            steps {
                container('kaniko') {
                    script {
			    echo "Docker Repo: ${env.DOCKER_REPO}"
                            echo "Tag: ${env.DOCKER_TAGS}"
                            sh '''
                            /kaniko/executor --context /home/jenkins/agent/workspace/python-app --dockerfile Dockerfile --destination docker.io/${env.DOCKER_REPO}:${env.DOCKER_TAGS}
                            '''
                    }
                }
            }
	}	
    }
}
