pipeline {
    agent any
    environment {
        APP_NAME = "python-app"
        REPOSITORY = "https://github.com/suleonal/python-web-app.git"
        VERSION = "1.0.${env.BUILD_ID}"
        FULL_CHART_NAME = "${APP_NAME}-${VERSION}.tgz"
    }
    stages {
	stage('Print Working Directory and List Files') {
            steps {
                script {
                    sh 'pwd'
                    
                    sh 'ls -l'
                }
            }
        }
	stage('Kaniko Build & Push Image') {
            steps {
                container('kaniko') {
                    script {
                        sh '''
			/kaniko/executor --context /home/jenkins/agent/workspace/python-app/applications/python-web-app --dockerfile Dockerfile --destination suleonal/python-app:1.0.6
                        '''
                    }
                }
            }
        }
    }
}
