pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins-kaniko-pod.yaml'  // 'builder.yaml' dosyasını pipeline içinde belirtirsiniz
        }
    }
    environment {
        APP_NAME = "python-app"
        REPOSITORY = "https://github.com/suleonal/python-web-app.git"
        VERSION = "1.0.${env.BUILD_ID}"
        FULL_CHART_NAME = "${APP_NAME}-${VERSION}.tgz"
    }
    stages {
	stage('Kaniko Build & Push Image') {
            steps {
                container('kaniko') {
                    script {
                        sh '''
                        /kaniko/executor --dockerfile `pwd`/Dockerfile \
                                         --context `pwd` \
                                         --destination=suleonal/python-app:1.0.7
                        '''
                    }
                }
            }
        }
    }
}
