replicaCount: 1

image:
  repository: suleonal/python-app
  tag: "1.0.6"
  pullPolicy: IfNotPresent

postgres:
  host: postgres-postgresql.databases.svc.cluster.local
  port: 5432

redis:
  host: redis-master.databases.svc.cluster.local
  port: 6379

service:
  port: 5000              # Kubernetes dışına açılacak port (LoadBalancer veya NodePort)
  targetPort: 5000
  nodePort: 30010
  type: NodePort
